# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SbomConvert < Formula
  desc "A tool to convert between different Software Bill of Materials (SBOM) formats."
  homepage "https://github.com/manifest-cyber/sbom-convert"
  version "0.0.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/manifest-cyber/sbom-convert/releases/download/v0.0.2/sbom-convert_darwin_arm64.tar.gz"
      sha256 "d2e5104514103fa05e5908afd413d8bda0c0a4263b6200b8ed14121bd787c7fb"

      def install
        bin.install "sbom-convert"
        bash_completion.install "completions/sbom-convert.bash" => "sbom-convert"
        zsh_completion.install "completions/sbom-convert.zsh" => "_sbom-convert"
        fish_completion.install "completions/sbom-convert.fish"
        man1.install "manpages/sbom-convert.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/manifest-cyber/sbom-convert/releases/download/v0.0.2/sbom-convert_darwin_x86_64.tar.gz"
      sha256 "0657a0e4dc002ff8b65e6954b8efebae0560634ce962cad2ab46a37bb0b49ee5"

      def install
        bin.install "sbom-convert"
        bash_completion.install "completions/sbom-convert.bash" => "sbom-convert"
        zsh_completion.install "completions/sbom-convert.zsh" => "_sbom-convert"
        fish_completion.install "completions/sbom-convert.fish"
        man1.install "manpages/sbom-convert.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/manifest-cyber/sbom-convert/releases/download/v0.0.2/sbom-convert_linux_arm64.tar.gz"
      sha256 "a79afdfff635b5ecf893b70749753ceec86ca36a6edb89aaa6766f06a529d3c0"

      def install
        bin.install "sbom-convert"
        bash_completion.install "completions/sbom-convert.bash" => "sbom-convert"
        zsh_completion.install "completions/sbom-convert.zsh" => "_sbom-convert"
        fish_completion.install "completions/sbom-convert.fish"
        man1.install "manpages/sbom-convert.1.gz"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/manifest-cyber/sbom-convert/releases/download/v0.0.2/sbom-convert_linux_armv7.tar.gz"
      sha256 "86c5af6c265b3f748414160b02ffa3bcb25b270c7060036f76256d54f724ebb5"

      def install
        bin.install "sbom-convert"
        bash_completion.install "completions/sbom-convert.bash" => "sbom-convert"
        zsh_completion.install "completions/sbom-convert.zsh" => "_sbom-convert"
        fish_completion.install "completions/sbom-convert.fish"
        man1.install "manpages/sbom-convert.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/manifest-cyber/sbom-convert/releases/download/v0.0.2/sbom-convert_linux_x86_64.tar.gz"
      sha256 "7a5435ae180b7e7a3b8efff2cdbd978c4a9ff54fd7df71907b932c56beb5f3fd"

      def install
        bin.install "sbom-convert"
        bash_completion.install "completions/sbom-convert.bash" => "sbom-convert"
        zsh_completion.install "completions/sbom-convert.zsh" => "_sbom-convert"
        fish_completion.install "completions/sbom-convert.fish"
        man1.install "manpages/sbom-convert.1.gz"
      end
    end
  end
end
