# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SbomConvert < Formula
  desc "A tool to convert between different Software Bill of Materials (SBOM) formats."
  homepage "https://github.com/bom-squad/sbom-convert"
  version "0.0.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bom-squad/sbom-convert/releases/download/v0.0.1/sbom-convert_darwin_arm64.tar.gz"
      sha256 "2cfd21c612f2f248a5d9fc6d8c3f31b2d126b2696c1cd7b70a914d644e969239"

      def install
        bin.install "sbom-convert"
        bash_completion.install "completions/sbom-convert.bash" => "sbom-convert"
        zsh_completion.install "completions/sbom-convert.zsh" => "_sbom-convert"
        fish_completion.install "completions/sbom-convert.fish"
        man1.install "manpages/sbom-convert.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bom-squad/sbom-convert/releases/download/v0.0.1/sbom-convert_darwin_amd64.tar.gz"
      sha256 "32f240966ea8a2716e8a39febf30b1203a207f683f0ee5a6139c6ad4c37ef634"

      def install
        bin.install "sbom-convert"
        bash_completion.install "completions/sbom-convert.bash" => "sbom-convert"
        zsh_completion.install "completions/sbom-convert.zsh" => "_sbom-convert"
        fish_completion.install "completions/sbom-convert.fish"
        man1.install "manpages/sbom-convert.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/bom-squad/sbom-convert/releases/download/v0.0.1/sbom-convert_linux_armv7.tar.gz"
      sha256 "b8a6f576fa667be018c0c896941b9ba42668f638b9b9be1d65eeecd4713bc16e"

      def install
        bin.install "sbom-convert"
        bash_completion.install "completions/sbom-convert.bash" => "sbom-convert"
        zsh_completion.install "completions/sbom-convert.zsh" => "_sbom-convert"
        fish_completion.install "completions/sbom-convert.fish"
        man1.install "manpages/sbom-convert.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bom-squad/sbom-convert/releases/download/v0.0.1/sbom-convert_linux_amd64.tar.gz"
      sha256 "5f981720768c9bad6e8a778e341d50ead40a894f3a906478a0d5b47816396398"

      def install
        bin.install "sbom-convert"
        bash_completion.install "completions/sbom-convert.bash" => "sbom-convert"
        zsh_completion.install "completions/sbom-convert.zsh" => "_sbom-convert"
        fish_completion.install "completions/sbom-convert.fish"
        man1.install "manpages/sbom-convert.1.gz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bom-squad/sbom-convert/releases/download/v0.0.1/sbom-convert_linux_arm64.tar.gz"
      sha256 "0e46591195d93b19ef8615d3a88c26c4eac0b9b0e52dbd55feb94dbe9ebd14ac"

      def install
        bin.install "sbom-convert"
        bash_completion.install "completions/sbom-convert.bash" => "sbom-convert"
        zsh_completion.install "completions/sbom-convert.zsh" => "_sbom-convert"
        fish_completion.install "completions/sbom-convert.fish"
        man1.install "manpages/sbom-convert.1.gz"
      end
    end
  end
end
