# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SbomConvert < Formula
  desc "A tool to convert between different Software Bill of Materials (SBOM) formats."
  homepage "https://github.com/bom-squad/sbom-convert"
  version "0.0.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bom-squad/sbom-convert/releases/download/v0.0.1/sbom-convert_darwin_arm64.tar.gz"
      sha256 "3455bd5c5f7cb587d6ffc39c344e84db62caac85521d93d97c42b90393fc3192"

      def install
        bin.install "sbom-convert"
        bash_completion.install "completions/sbom-convert.bash" => "sbom-convert"
        zsh_completion.install "completions/sbom-convert.zsh" => "_sbom-convert"
        fish_completion.install "completions/sbom-convert.fish"
        man1.install "manpages/sbom-convert.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bom-squad/sbom-convert/releases/download/v0.0.1/sbom-convert_darwin_x86_64.tar.gz"
      sha256 "e354246fe56440b715d66e3f8643c16a8c078e1dc1439572c6d0832010caffbd"

      def install
        bin.install "sbom-convert"
        bash_completion.install "completions/sbom-convert.bash" => "sbom-convert"
        zsh_completion.install "completions/sbom-convert.zsh" => "_sbom-convert"
        fish_completion.install "completions/sbom-convert.fish"
        man1.install "manpages/sbom-convert.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/bom-squad/sbom-convert/releases/download/v0.0.1/sbom-convert_linux_armv7.tar.gz"
      sha256 "8e1808fe4873102884c9a3a04b5a1211a6dd65d3e24b5fa0a6515e1a2607cbd1"

      def install
        bin.install "sbom-convert"
        bash_completion.install "completions/sbom-convert.bash" => "sbom-convert"
        zsh_completion.install "completions/sbom-convert.zsh" => "_sbom-convert"
        fish_completion.install "completions/sbom-convert.fish"
        man1.install "manpages/sbom-convert.1.gz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bom-squad/sbom-convert/releases/download/v0.0.1/sbom-convert_linux_arm64.tar.gz"
      sha256 "ddc0e0563fdfa353f4a284825a16eb2b8e46961f2c616e4a98e1363f33dfe35d"

      def install
        bin.install "sbom-convert"
        bash_completion.install "completions/sbom-convert.bash" => "sbom-convert"
        zsh_completion.install "completions/sbom-convert.zsh" => "_sbom-convert"
        fish_completion.install "completions/sbom-convert.fish"
        man1.install "manpages/sbom-convert.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bom-squad/sbom-convert/releases/download/v0.0.1/sbom-convert_linux_x86_64.tar.gz"
      sha256 "336693bee0a954a0fac4c6ebe87d0d528ab5ef507ec0572696ea2cd56dc574c8"

      def install
        bin.install "sbom-convert"
        bash_completion.install "completions/sbom-convert.bash" => "sbom-convert"
        zsh_completion.install "completions/sbom-convert.zsh" => "_sbom-convert"
        fish_completion.install "completions/sbom-convert.fish"
        man1.install "manpages/sbom-convert.1.gz"
      end
    end
  end
end
